### ISSUE TITLE
Error while executing the program

### ISSUE THREAD

**Issue by Junaid199f** [jose-tapia/nn-hh-umhs-cec22#2]
Hi! Congratulations for this wonderful work and idea. I have some problem while running the code and noticed that some of the configuration files for running the experiments are missing.  Is this code just for processing results or also includes complete files for reproducing the results.  While running the experiment.py file I am facing some problems. Could you please help me fix this issue. Thanks

Regards

**Comment by jose-tapia** [comment]
Hello @Junaid199f,

Thank you for your comments and bring up the issue to us! We really appreciate it.

I tested the experiments and include a jupyter notebook with detailed descriptions about how modify and run the experiments; Please find it in [google_colab_notebook_CUSTOMHyS.ipynb](https://github.com/jose-tapia/nn-hh-umhs-cec22/blob/main/google_colab_notebook_CUSTOMHyS.ipynb)

Here is a google colab notebook that runs the notebook: [Notebook](https://colab.research.google.com/drive/1NI7FM0XU3ldRrd9bcnLGgPFS7e0tmEZZ?usp=sharing)

Let us know if the issue persists!

Best regards,
José Manuel

**Comment by Junaid199f** [comment]
Thanks a lot.

Regards,
Muhammad Junaid Ali
